"""
Integration tests for speaker diarization quality improvements.

This module tests the complete diarization pipeline with quality
improvements including embedding validation, segment filtering,
and enhanced configuration.
"""

import pytest
import numpy as np
import tempfile
import wave
from unittest.mock import Mock, AsyncMock, patch, MagicMock
from pathlib import Path
import sys

# Add src to path for imports
src_path = Path(__file__).parent.parent.parent
sys.path.insert(0, str(src_path))

from diarization.diarization_client import (
    DiarizationClient,
    DiarizationResult,
    SpeakerSegment,
    SpeakerMemory,
    diarization_worker
)
from diarization.embedding_validator import EmbeddingQualityValidator


def create_test_audio(duration_seconds: float = 6.0, sample_rate: int = 16000) -> str:
    """Create a test WAV file with synthetic audio."""
    path = tempfile.mktemp(suffix=".wav")
    t = np.linspace(0, duration_seconds, int(sample_rate * duration_seconds), dtype=np.float32)
    audio = np.sin(2 * np.pi * 440 * t) * 0.5
    pcm16 = (audio * 32767.0).astype(np.int16)
    with wave.open(path, "wb") as wf:
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        wf.setnchannels(1)
        low_conf_callback.reset_mock()
        
        # Add another speaker
        different_embedding = np.random.randn(512).astype(np.float32) * -1
        memory.identify(different_embedding)
        
        # Now identify with a slightly different embedding (should be low confidence)
        similar_but_different = different_embedding * 0.8  # Will have lower similarity
        speaker_id, confidence, _ = memory.identify(similar_but_different)
        
        # This should create a new speaker (low similarity) or match with low confidence
        # The exact behavior depends on threshold, but we can verify callbacks are used
        stats = memory.get_stats()
        assert stats["identifications"] >= 3
    
    def test_get_stats_includes_validator_stats(self):
        """Test that get_stats includes validator statistics."""
        memory = SpeakerMemory()
        
        # Process some embeddings
        memory.identify(np.random.randn(512).astype(np.float32))
        memory.identify(np.zeros(512, dtype=np.float32))
        
        stats = memory.get_stats()
        
        assert "validator_stats" in stats
        assert stats["validator_stats"]["total_checked"] == 2
        assert stats["validator_stats"]["invalid_count"] == 1
    
    def test_multiple_speakers_with_validation(self):
        """Test creating multiple speakers with validation enabled."""
        memory = SpeakerMemory()
        
        # Create several different speakers
        embeddings = [
            np.random.randn(512).astype(np.float32),
            np.random.randn(512).astype(np.float32) * -1,
            np.random.randn(512).astype(np.float32) * 2,
        ]
        
        speaker_ids = []
        for emb in embeddings:
            speaker_id, confidence, _ = memory.identify(emb)
            speaker_ids.append(speaker_id)
        
        # All should be different speakers
        assert len(set(speaker_ids)) == 3
        assert len(memory.centroids) == 3
        
        # Stats should reflect this
        stats = memory.get_stats()
        assert stats["new_speakers"] == 3
        assert stats["valid_embeddings"] == 3
    
    def test_speaker_matching_with_validation(self):
        """Test that speaker matching works correctly with validation."""
        memory = SpeakerMemory(threshold=0.70)
        
        # Create first speaker
        embedding1 = np.random.randn(512).astype(np.float32)
        speaker1_id, _, _ = memory.identify(embedding1)
        
        # Same speaker again (should match with high confidence)
        speaker1_again, conf, _ = memory.identify(embedding1)
        assert speaker1_again == speaker1_id
        assert conf >= 0.70  # Should meet threshold
        
        # Different speaker
        embedding2 = np.random.randn(512).astype(np.float32) * -1
        speaker2_id, _, _ = memory.identify(embedding2)
        assert speaker2_id != speaker1_id
        
        # Back to first speaker
        speaker1_back, conf_back, _ = memory.identify(embedding1)
        assert speaker1_back == speaker1_id
        
        # Stats
        stats = memory.get_stats()
        assert stats["identifications"] == 4
        assert stats["matches"] == 2  # Two matches to speaker_0
        assert stats["new_speakers"] == 1  # One new speaker (speaker_1)


class TestDiarizationClientWithQualityImprovements:
    """Tests for DiarizationClient with quality improvements."""
    
    @pytest.fixture
    def mock_processor(self):
        """Create a mock PROCESSOR."""
        processor = Mock()
        processor.send_data = AsyncMock()
        return processor
    
    @pytest.fixture
    def mock_state(self, mock_processor):
        """Create a mock STATE with required attributes."""
        from pipeline.main import TranscriberState
        state = TranscriberState()
        state.buffer_rate = 16000
        state.buffer_start_ts = 0.0
        state.diarization_buffer_start_ts = 0.0
        state.diarization_audio_buffer = np.zeros((0,), dtype=np.float32)
        state.pending_temp_files = {}
        state.diarization_window_timestamps = {}
        state.diarization_client = Mock()
        state.diarization_client.remove_in_flight_request = Mock()
        return state
    
    def test_client_initialization_with_quality_params(self):
        """Test DiarizationClient initialization with quality parameters."""
        client = DiarizationClient(
            hf_token="test-token",
            threshold=0.75,
            min_segment_duration=0.3
        )
        
        assert client.threshold == 0.75
        assert client.min_segment_duration == 0.3
    
    def test_client_with_custom_validator(self):
        """Test DiarizationClient with custom embedding validator."""
        custom_validator = EmbeddingQualityValidator(
            min_embedding_norm=0.5,
            log_invalid=False
        )
        
        client = DiarizationClient(
            hf_token="test-token",
            embedding_validator=custom_validator
        )
        
        assert client.embedding_validator is custom_validator
    
    def test_client_with_monitoring_callbacks(self):
        """Test DiarizationClient with monitoring callbacks."""
        invalid_cb = Mock()
        low_conf_cb = Mock()
        
        client = DiarizationClient(
            hf_token="test-token",
            on_invalid_embedding=invalid_cb,
            on_low_confidence=low_conf_cb
        )
        
        assert client.on_invalid_embedding is invalid_cb
        assert client.on_low_confidence is low_conf_cb
    
    def test_update_params_with_quality_settings(self):
        """Test updating client parameters with quality settings."""
        client = DiarizationClient(hf_token="test-token")
        
        client.update_params(
            threshold=0.80,
            min_segment_duration=0.4
        )
        
        assert client.threshold == 0.80
        assert client.min_segment_duration == 0.4
    
    def test_get_stats_returns_speaker_memory_stats(self):
        """Test that get_stats returns speaker memory statistics."""
        client = DiarizationClient(hf_token="test-token")
        
        # Initialize to create speaker memory
        import asyncio
        asyncio.run(client.initialize())
        
        stats = client.get_stats()
        
        # Should have validation stats
        assert "identifications" in stats
        assert "valid_embeddings" in stats
        assert "invalid_embeddings" in stats
    
    def test_client_reset_clears_quality_stats(self):
        """Test that reset clears quality-related statistics."""
        client = DiarizationClient(hf_token="test-token")
        
        import asyncio
        asyncio.run(client.initialize())
        
        # Add some data
        if client._speaker_memory:
            client._speaker_memory.identify(np.random.randn(512).astype(np.float32))
            client._speaker_memory.identify(np.zeros(512, dtype=np.float32))
        
        # Reset
        client.reset()
        
        # Check stats are cleared
        stats = client.get_stats()
        assert stats["identifications"] == 0


class TestSegmentDurationFiltering:
    """Tests for segment duration filtering in the worker."""
    
    def test_short_segment_filtering_in_worker(self):
        """Test that short segments are filtered in the worker logic."""
        # This tests the MIN_SEGMENT_DURATION constant and logic
        MIN_SEGMENT_DURATION = 0.5
        
        # Short segment should be skipped
        short_duration = 0.3
        assert short_duration < MIN_SEGMENT_DURATION
        
        # Long segment should be processed
        long_duration = 1.0
        assert long_duration >= MIN_SEGMENT_DURATION
    
    def test_segment_duration_in_speaker_memory(self):
        """Test that SpeakerMemory has min_segment_duration parameter."""
        memory = SpeakerMemory(min_segment_duration=0.3)
        
        assert memory.min_segment_duration == 0.3
        
        # Test with different value
        memory2 = SpeakerMemory(min_segment_duration=1.0)
        assert memory2.min_segment_duration == 1.0


class TestPyannotePipelineConfiguration:
    """Tests for pyannote pipeline configuration."""
    
    def test_pipeline_parameters_structure(self):
        """Test that pipeline parameters have correct structure."""
        # These are the parameters from the improved diarization_worker
        clustering_params = {
            "method": "centroid",
            "min_cluster_size": 12,
            "threshold": 0.7045654963945799,
        }
        
        segmentation_params = {
            "min_duration_off": 0.0,
        }
        
        # Verify structure
        assert "method" in clustering_params
        assert "min_cluster_size" in clustering_params
        assert "threshold" in clustering_params
        assert "min_duration_off" in segmentation_params
    
    def test_clustering_threshold_value(self):
        """Test that clustering threshold is in valid range."""
        threshold = 0.7045654963945799
        
        # Threshold should be between 0 and 1
        assert 0 < threshold < 1


if __name__ == "__main__":
    pytest.main([__file__, "-v"])